name: protoc_builder
description: A build script for compiling Protocol Buffers without needing to manually install protoc or the protoc_plugin.
version: 0.2.1+1
repository: https://github.com/pikaju/dart-protoc-builder

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  archive: ^3.1.6
  build: ^2.1.1
  http: ^0.13.4
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
